#!/bin/bash

echo "Installing Consul"

set +e
consul --version
consul_status=$?
set -e

if [ ${consul_status} -ne 0 ]; then
  wget https://releases.hashicorp.com/consul/0.7.5/consul_0.7.5_darwin_amd64.zip -O /tmp/consul.zip && \
  unzip /tmp/consul.zip -d /usr/local/bin
  rm /tmp/consul.zip
fi

echo "Setting up Postgres"
brew link postgresql@9.6 --force
brew services restart postgresql@9.6
sleep 1
set +e
psql -U postgres -c "\l"
postgres_role_status=$?
set -e
if [ ${postgres_role_status} -ne 0 ]; then
  psql -d postgres -c "CREATE ROLE postgres WITH SUPERUSER LOGIN PASSWORD 'password';" 
fi

echo "Setting up Mysql"
brew services restart mysql
sleep 10
mysql -u root -e "CREATE DATABASE IF NOT EXISTS routing_api_test;"
mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"


